version: '3.8'

services:
  flask_database:
    image: postgres:15
    container_name: flask_database
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sheetflow
    volumes:
      - flask_database_data:/var/lib/postgresql/data
    ports:
      - "5477:5432"
    command: 
      - "postgres"
      - "-c"
      - "listen_addresses=*"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "work_mem=8MB"
      - "-c"
      - "log_min_messages=WARNING"

  flask_sheetflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_sheetflow
    depends_on:
      - flask_database
    restart: always
    ports:
      - "8000:8000"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@flask_database:5432/sheetflow
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,flask_sheetflow
    volumes:
      - .:/app
    command: gunicorn --config gunicorn.conf.py -b 0.0.0.0:8000 manage:app

volumes:
  flask_database_data: