"""adjust coluns reference entry install numbers and notification workers

Revision ID: 00f8d8809f7c
Revises: 5cc8579ef7a0
Create Date: 2026-01-12 18:21:24.614662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00f8d8809f7c'
down_revision: Union[str, Sequence[str], None] = '5cc8579ef7a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installment_payment', sa.Column('paid_at', sa.DateTime(), nullable=True))
    op.add_column('notification_jobs', sa.Column('installment_numbers', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_jobs', 'installment_numbers')
    op.drop_column('installment_payment', 'paid_at')
    # ### end Alembic commands ###
