"""adiiconado a coluna do financeiro

Revision ID: 045efde74858
Revises: 5e5c6359cd7a
Create Date: 2025-12-11 18:44:35.034656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '045efde74858'
down_revision: Union[str, Sequence[str], None] = '5e5c6359cd7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date_contract', sa.Date(), nullable=False),
    sa.Column('document', sa.String(length=255), nullable=False),
    sa.Column('installment_numbers', sa.Integer(), nullable=False),
    sa.Column('total', sa.Numeric(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finance_out_flow_box',
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finance_out_flow_box')
    op.drop_table('finance')
    # ### end Alembic commands ###
