"""adjust in table installment_payment

Revision ID: 05fb5ce77fdb
Revises: 93e82d2a7bf5
Create Date: 2026-01-08 19:56:07.412280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05fb5ce77fdb'
down_revision: Union[str, Sequence[str], None] = '93e82d2a7bf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installment_payment', sa.Column('installment_number', sa.Integer(), nullable=False))
    op.drop_column('installment_payment', 'installment_numbers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installment_payment', sa.Column('installment_numbers', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('installment_payment', 'installment_number')
    # ### end Alembic commands ###
