"""add prazo

Revision ID: 0cd8288bc07e
Revises: 1a0b69a04ca5
Create Date: 2026-01-16 13:37:43.833188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cd8288bc07e'
down_revision: Union[str, Sequence[str], None] = '1a0b69a04ca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mappings_groups', sa.Column('prazo', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mappings_groups', 'prazo')
    # ### end Alembic commands ###
