"""ajuste na tabela groups

Revision ID: 331c0270e50f
Revises: 8187cc6a0250
Create Date: 2025-12-09 12:16:08.331929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '331c0270e50f'
down_revision: Union[str, Sequence[str], None] = '8187cc6a0250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_groups_custom_columns_gin'), table_name='groups', postgresql_using='gin')
    op.drop_index(op.f('ix_groups_data_gin'), table_name='groups', postgresql_using='gin')
    op.drop_column('groups', 'data')
    op.drop_column('groups', 'custom_columns')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('custom_columns', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('groups', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_groups_data_gin'), 'groups', ['data'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_groups_custom_columns_gin'), 'groups', ['custom_columns'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
