"""add number process

Revision ID: 3ee10320b51c
Revises: d0fe21a1494b
Create Date: 2026-01-06 08:40:47.480279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ee10320b51c'
down_revision: Union[str, Sequence[str], None] = 'd0fe21a1494b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mappings_groups', sa.Column('numero_processo', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mappings_groups', 'numero_processo')
    # ### end Alembic commands ###
