"""ajutes no outbox

Revision ID: 4d694a573bbb
Revises: cfc02cf9d51c
Create Date: 2025-12-22 20:29:08.415229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d694a573bbb'
down_revision: Union[str, Sequence[str], None] = 'cfc02cf9d51c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finance_out_flow_box', sa.Column('installment_numbers', sa.Integer(), nullable=True))
    op.add_column('finance_out_flow_box', sa.Column('date_flow', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finance_out_flow_box', 'date_flow')
    op.drop_column('finance_out_flow_box', 'installment_numbers')
    # ### end Alembic commands ###
