"""adjust columns in install numbers

Revision ID: 5cc8579ef7a0
Revises: d7e1e80a88a1
Create Date: 2026-01-12 18:10:30.790911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cc8579ef7a0'
down_revision: Union[str, Sequence[str], None] = 'd7e1e80a88a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installment_payment', sa.Column('due_date', sa.DateTime(), nullable=False))
    op.drop_column('installment_payment', 'paid_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installment_payment', sa.Column('paid_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('installment_payment', 'due_date')
    # ### end Alembic commands ###
