"""ajuste na tabela mappgins grupos

Revision ID: 5e5c6359cd7a
Revises: c10a46bfd03b
Create Date: 2025-12-09 12:27:41.068240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e5c6359cd7a'
down_revision: Union[str, Sequence[str], None] = 'c10a46bfd03b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mappings_groups', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('mappings_groups', 'depedencias_pid',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('mappings_groups', 'localidade',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('mappings_groups', 'nome',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('mappings_groups', 'contato',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('mappings_groups', 'pasta_drive',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('mappings_groups', 'cpf_cnpj',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('mappings_groups', 'senha_portal',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('mappings_groups', 'aba_plataforma',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('mappings_groups', 'status',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('mappings_groups', 'data_atual',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('mappings_groups', 'data_intimacao',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('mappings_groups', 'prazo',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('mappings_groups', 'data_final',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('mappings_groups', 'oficio',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('mappings_groups', 'valor_indenizacao',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('mappings_groups', 'valor_honorario',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('mappings_groups', 'observacao',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mappings_groups', 'observacao',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('mappings_groups', 'valor_honorario',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('mappings_groups', 'valor_indenizacao',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('mappings_groups', 'oficio',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('mappings_groups', 'data_final',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('mappings_groups', 'prazo',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('mappings_groups', 'data_intimacao',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('mappings_groups', 'data_atual',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('mappings_groups', 'status',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('mappings_groups', 'aba_plataforma',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('mappings_groups', 'senha_portal',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('mappings_groups', 'cpf_cnpj',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('mappings_groups', 'pasta_drive',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('mappings_groups', 'contato',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('mappings_groups', 'nome',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('mappings_groups', 'localidade',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('mappings_groups', 'depedencias_pid',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('mappings_groups', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
