"""add workers courtes deadlines

Revision ID: 6398654ed74e
Revises: 0cd8288bc07e
Create Date: 2026-01-16 14:11:44.257904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6398654ed74e'
down_revision: Union[str, Sequence[str], None] = '0cd8288bc07e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_court_deadline',
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contato', sa.String(), nullable=False),
    sa.Column('document', sa.String(), nullable=False),
    sa.Column('prazo', sa.Date(), nullable=False),
    sa.Column('groups_id', sa.Uuid(), nullable=False),
    sa.Column('mappings_groups_id', sa.Uuid(), nullable=False),
    sa.Column('executed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('court_deadline',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contato', sa.String(), nullable=False),
    sa.Column('document', sa.String(), nullable=False),
    sa.Column('prazo', sa.Date(), nullable=False),
    sa.Column('charged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('groups_id', sa.Uuid(), nullable=False),
    sa.Column('mappings_groups_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['groups_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['mappings_groups_id'], ['mappings_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('court_deadline')
    op.drop_table('notification_court_deadline')
    # ### end Alembic commands ###
