"""ajuste tables mappings

Revision ID: 705815744398
Revises: 4d694a573bbb
Create Date: 2025-12-30 16:15:59.463561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '705815744398'
down_revision: Union[str, Sequence[str], None] = '4d694a573bbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mappings_groups', sa.Column('documento', sa.String(length=20), nullable=True))
    op.add_column('mappings_groups', sa.Column('origem', sa.String(length=255), nullable=True))
    op.add_column('mappings_groups', sa.Column('senha', sa.String(length=255), nullable=True))
    op.add_column('mappings_groups', sa.Column('orgao_julgador', sa.String(length=255), nullable=True))
    op.add_column('mappings_groups', sa.Column('contra_parte', sa.String(length=255), nullable=True))
    op.add_column('mappings_groups', sa.Column('a_ser_feito', sa.Numeric(), nullable=True))
    op.add_column('mappings_groups', sa.Column('andamento', sa.String(length=255), nullable=True))
    op.alter_column('mappings_groups', 'pasta_drive',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Boolean(),
               nullable=False)
    op.drop_column('mappings_groups', 'oficio')
    op.drop_column('mappings_groups', 'cpf_cnpj')
    op.drop_column('mappings_groups', 'senha_portal')
    op.drop_column('mappings_groups', 'depedencias_pid')
    op.drop_column('mappings_groups', 'valor_honorario')
    op.drop_column('mappings_groups', 'data_intimacao')
    op.drop_column('mappings_groups', 'prazo')
    op.drop_column('mappings_groups', 'aba_plataforma')
    op.drop_column('mappings_groups', 'status')
    op.drop_column('mappings_groups', 'valor_indenizacao')
    op.drop_column('mappings_groups', 'data_final')
    op.drop_column('mappings_groups', 'data_atual')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mappings_groups', sa.Column('data_atual', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('mappings_groups', sa.Column('data_final', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('mappings_groups', sa.Column('valor_indenizacao', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('mappings_groups', sa.Column('status', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('mappings_groups', sa.Column('aba_plataforma', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('mappings_groups', sa.Column('prazo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('mappings_groups', sa.Column('data_intimacao', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('mappings_groups', sa.Column('valor_honorario', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('mappings_groups', sa.Column('depedencias_pid', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('mappings_groups', sa.Column('senha_portal', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('mappings_groups', sa.Column('cpf_cnpj', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('mappings_groups', sa.Column('oficio', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('mappings_groups', 'pasta_drive',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('mappings_groups', 'andamento')
    op.drop_column('mappings_groups', 'a_ser_feito')
    op.drop_column('mappings_groups', 'contra_parte')
    op.drop_column('mappings_groups', 'orgao_julgador')
    op.drop_column('mappings_groups', 'senha')
    op.drop_column('mappings_groups', 'origem')
    op.drop_column('mappings_groups', 'documento')
    # ### end Alembic commands ###
