"""add columns groups

Revision ID: 8187cc6a0250
Revises: 8242eddd326a
Create Date: 2025-12-05 16:05:20.248344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8187cc6a0250'
down_revision: Union[str, Sequence[str], None] = '8242eddd326a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('custom_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_groups_custom_columns_gin', 'groups', ['custom_columns'], unique=False, postgresql_using='gin')
    op.create_index('ix_groups_data_gin', 'groups', ['data'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_groups_name'), 'groups', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_groups_name'), table_name='groups')
    op.drop_index('ix_groups_data_gin', table_name='groups', postgresql_using='gin')
    op.drop_index('ix_groups_custom_columns_gin', table_name='groups', postgresql_using='gin')
    op.drop_table('groups')
    # ### end Alembic commands ###
