"""adjust table installment_payment

Revision ID: 93e82d2a7bf5
Revises: 055ea15f6208
Create Date: 2026-01-08 19:45:57.173847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93e82d2a7bf5'
down_revision: Union[str, Sequence[str], None] = '055ea15f6208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installment_payment', sa.Column('installment_numbers', sa.Integer(), nullable=False))
    op.add_column('installment_payment', sa.Column('paid_at', sa.DateTime(), nullable=False))
    op.add_column('installment_payment', sa.Column('finance_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'installment_payment', 'finance', ['finance_id'], ['id'])
    op.drop_column('installment_payment', 'date_contract')
    op.drop_column('installment_payment', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installment_payment', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('installment_payment', sa.Column('date_contract', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'installment_payment', type_='foreignkey')
    op.drop_column('installment_payment', 'finance_id')
    op.drop_column('installment_payment', 'paid_at')
    op.drop_column('installment_payment', 'installment_numbers')
    # ### end Alembic commands ###
