"""ajuste na tabela groups com mappeamento

Revision ID: c10a46bfd03b
Revises: 331c0270e50f
Create Date: 2025-12-09 12:23:11.587069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c10a46bfd03b'
down_revision: Union[str, Sequence[str], None] = '331c0270e50f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mappings_groups',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('depedencias_pid', sa.String(length=255), nullable=False),
    sa.Column('localidade', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('contato', sa.String(length=255), nullable=False),
    sa.Column('pasta_drive', sa.String(length=255), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=255), nullable=False),
    sa.Column('senha_portal', sa.String(length=255), nullable=False),
    sa.Column('aba_plataforma', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('data_atual', sa.String(length=255), nullable=False),
    sa.Column('data_intimacao', sa.String(length=255), nullable=False),
    sa.Column('prazo', sa.String(length=255), nullable=False),
    sa.Column('data_final', sa.String(length=255), nullable=False),
    sa.Column('oficio', sa.String(length=255), nullable=False),
    sa.Column('valor_indenizacao', sa.String(length=255), nullable=False),
    sa.Column('valor_honorario', sa.String(length=255), nullable=False),
    sa.Column('observacao', sa.String(length=255), nullable=False),
    sa.Column('groups_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['groups_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mappings_groups')
    # ### end Alembic commands ###
