"""ajuste no mappings groups

Revision ID: cfc02cf9d51c
Revises: 045efde74858
Create Date: 2025-12-19 19:55:09.648228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfc02cf9d51c'
down_revision: Union[str, Sequence[str], None] = '045efde74858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column(
        'mappings_groups',
        'data_atual',
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Date(),
        postgresql_using="data_atual::date",
        existing_nullable=True,
    )
    op.alter_column(
        'mappings_groups',
        'data_intimacao',
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Date(),
        postgresql_using="data_intimacao::date",
        existing_nullable=True,
    )
    op.alter_column(
        'mappings_groups',
        'data_final',
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Date(),
        postgresql_using="data_final::date",
        existing_nullable=True,
    )
    op.alter_column(
        'mappings_groups',
        'valor_indenizacao',
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Numeric(),
        postgresql_using="valor_indenizacao::numeric",
        existing_nullable=True,
    )
    op.alter_column(
        'mappings_groups',
        'valor_honorario',
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Numeric(),
        postgresql_using="valor_honorario::numeric",
        existing_nullable=True,
    )
    op.drop_column('mappings_groups', 'nome')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mappings_groups', sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('mappings_groups', 'valor_honorario',
               existing_type=sa.Numeric(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('mappings_groups', 'valor_indenizacao',
               existing_type=sa.Numeric(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('mappings_groups', 'data_final',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('mappings_groups', 'data_intimacao',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('mappings_groups', 'data_atual',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
