"""alter mappigns groups

Revision ID: d0fe21a1494b
Revises: 705815744398
Create Date: 2026-01-03 17:03:53.307642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0fe21a1494b'
down_revision: Union[str, Sequence[str], None] = '705815744398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mappings_groups', 'a_ser_feito',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mappings_groups', 'a_ser_feito',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    # ### end Alembic commands ###
