"""add colum for charged_at

Revision ID: f8812e008478
Revises: 00f8d8809f7c
Create Date: 2026-01-12 22:41:29.152694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8812e008478'
down_revision: Union[str, Sequence[str], None] = '00f8d8809f7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installment_payment', sa.Column('charged_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('installment_payment', 'charged_at')
    # ### end Alembic commands ###
